# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poc',
            fields=[
                ('f1', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
