# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poc',
            name='f1',
        ),
        migrations.AddField(
            model_name='poc',
            name='f2',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
